app/config/urls.py
import json
from ast import literal_eval

from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.urls import path, include

from config import settings
from posts.models import Post
from system.views import UserLoginView

User = get_user_model()


def get_literal_eval(eval_list):
    for data in eval_list:
        ret_list = literal_eval(data)

    return ret_list


def delete_exec(model, check_list):
    for obj in get_literal_eval(check_list):
        if model == 'account':
            User.objects.get(pk=int(obj['id'])).delete()
        elif model == 'post':
            Post.objects.get(pk=int(obj['id'])).delete()


def select_del(request):
    delete_exec(

        request.POST.get('tableIndex'),
        request.POST.getlist('checkList')
    )

    return HttpResponse(
        json.dumps({
            'result': 'success',
        }), content_type='application/json')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('del/', select_del, name='del'),
    path('', UserLoginView.as_view(), name='user-login'),
    path('system/', include('system.urls')),
    path('posts/', include('posts.urls')),
    path('items/', include('items.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/items/urls.py
from django.urls import path

from items.views import *

app_name = 'items'

urlpatterns = [
    path('', BreadsListView.as_view(), name='bread-list'),
    path('choice/', ChoiceListView.as_view(), name='choice-create'),
    path('package/<int:pk>/', PackageDetailView.as_view(), name='package-detail'),
    path('packageLike/', PackageLikeCreateView.as_view(), name='package-like'),
]

app/items/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class TimeStampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Breads(TimeStampedModel):
    name = models.CharField(max_length=100, help_text='상품 명', )
    desc = models.TextField(help_text='상품설명')
    price = models.PositiveIntegerField(help_text='상품설명', default=0)
    photo = models.ImageField(upload_to="%Y/%m/%d")


class UserChoices(TimeStampedModel):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    bread = models.ForeignKey(
        'items.Breads',
        on_delete=models.CASCADE,
    )
    package = models.ForeignKey(
        'items.Package',
        on_delete=models.CASCADE
    )


class Package(TimeStampedModel):
    pass


class PackageLike(TimeStampedModel):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    package = models.ForeignKey(
        'items.Package',
        on_delete=models.CASCADE,
    )

    class Meta:
        unique_together = ('user', 'package')

app/items/views.py
from datetime import datetime

from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from items.models import Breads, UserChoices, Package, PackageLike


class BreadsListView(ListView):
    model = Breads
    template_name = 'items/bread_list.html'
    context_object_name = 'bread_qs'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['package_qs'] = Package.objects.all()
        return context


class ChoiceListView(APIView):
    def post(self, request):
        data = request.data.get('row_data')
        pack_ins = Package.objects.create()
        for index in data:
            for field, value in index:
                bread_ins = Breads.objects.get(id=index.get('id'))
                UserChoices.objects.create(user=request.user, bread=bread_ins, package=pack_ins)
        return Response(status=status.HTTP_200_OK)


class PackageDetailView(DetailView):
    template_name = 'items/package_detail.html'
    model = Package

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_choice_qs'] = kwargs.get('object').userchoices_set.all()
        context['author'] = kwargs.get('object').userchoices_set.first()
        return context


class PackageLikeCreateView(APIView):
    def post(self, request):
        query_params = request.query_params
        previous_path = query_params.get('previous')
        package_pk = query_params.get('package')
        status = query_params.get('status')
        package_ins = Package.objects.get(pk=package_pk)
        ins, created = PackageLike.objects.get_or_create(user=request.user, package=package_ins)
        if status == 'delete':
            ins.delete()
        return redirect(previous_path)

app/templates/items/bread_list.html
{% extends "base.html" %}
{% block title %}제품 목록{% endblock %}
{% load bootstrap3 %}
{% load static %}

{% block contents %}
    <script type="text/javascript" src="{% static 'js/system/items/get_item_script.js' %}"></script>

    {% csrf_token %}
    <div class="container myTable">
        <div class="row row-offcanvas row-offcanvas-right">
            <div class="col-xs-12 col-sm-9">
                <div class="jumbotron">
                    <h1>빵묶음 챌린지!</h1>
                    <p>
                        만원의 상품을 만들어보세요.
                    </p>
                    <div>합계 가격 <input id="resultSumData" placeholder="0" style="color: red" disabled></div>
                    <div>
                        <button class="btn btn-primary" id="submitBtn" onclick="createChoices()">전송</button>
                    </div>
                </div>
                <div class="row"></div>
                {% for bread in bread_qs %}
                    <div class="col-xs-6 col-lg-4 includeCheckBox">
                        <div class="panel panel-default" value="{{ bread.id }}">
                            <input type="checkbox" name="breadCheck" value="{{ bread.id }}"
                                   class="hidden_chk">
                            <img class="bd-placeholder-img card-img-top" src="{{ bread.photo.url }}" alt="" WIDTH="250"
                                 HEIGHT="225">
                            <h4>{{ bread.name }} || {{ bread.id }}</h4>
                            <p>{{ bread.desc }}</p>
                            <p class="price">가격 : {{ bread.price }}</p>
                            <input type="checkbox" name="breadPrice" value="{{ bread.price }}"
                                   class="breadPrice hidden">
                            <input type="text" name="breadID" value="{{ bread.id }}" type="hidden">
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="col-xs-6 col-sm-3 sidebar-offcanvas">
                <div class="list-group">
                    {% for package_ins in package_qs %}
                        <a href="{% url 'items:package-detail' pk=package_ins.pk %}"
                           class="list-group-item">{{ package_ins.created_at }} || {{ package_ins.id }}
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/items/package_detail.html
{% extends 'base.html' %}
{% block title %}빵 묶음 상세{% endblock %}

{% load static %}
{% load bootstrap3 %}
{% block contents %}

    <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">빵 묶음 상세정보</div>
            <div class="panel-body">
                <table class="table table-bordered table-hover">
                    <tr>
                        <th><span style="color: red"></span>묶음 고유 번호</th>
                        <td>
                            <input type="text" name="id" value="{{ object.id }}" class="form-control" disabled>
                        </td>
                        <td colspan="2">
{#                        {{ package_like_status }}#}
{#                            {% if object. == 'True' %}#}
{#                                <form method="post"#}
{#                                      action="{% url 'items:package-like' %}?previous={% url 'items:package-detail' pk=object.pk %}&package={{ object.pk }}&status=delete">#}
{#                                    {% csrf_token %}#}
{#                                    {% if package_like_status %}#}
{#                                        <button class="btn btn-danger" style="width: 100%" value="{{ object.pk }}">좋아요#}
{#                                            해제#}
{#                                        </button>#}
{#                                    {% else %}#}
{#                                        <button class="btn btn-primary" style="width: 100%" value="{{ object.pk }}">좋아요#}
{#                                        </button>#}
{#                                    {% endif %}#}
{#                                </form>#}
{#                            {% else %}#}
{#                                <form method="post"#}
{#                                      action="{% url 'items:package-like' %}?previous={% url 'items:package-detail' pk=object.pk %}&package={{ object.pk }}&status=create">#}
{#                                    {% csrf_token %}#}
{##}
{#                                    <button class="btn btn-danger" style="width: 100%" value="{{ object.pk }}">좋아요 해제#}
{#                                    </button>#}
{#                                    <button class="btn btn-primary" style="width: 100%" value="{{ object.pk }}">좋아요#}
{#                                    </button>#}
{#                                </form>#}
{#                            {% endif %}#}
                        </td>
                    </tr>
                    <tr>
                        <th><span style="color: red"></span>생성일자</th>
                        <td>
                            <input type="date" class="form-control" name="due_date"
                                   value="{{ object.created_at|date:'Y-m-d' }}">
                        </td>
                        <th><span style="color: red"></span>작성자</th>
                        <td><input type="text" class="form-control" name="name" value="{{ author }}" disabled></td>
                    </tr>
                    {% for choice_ins in user_choice_qs %}
                        <tr>
                            <th><span style="color: red"></span>상품 명</th>
                            <td><p>{{ choice_ins.bread.name }}</p></td>
                            <th><span style="color: red"></span>상품 가격</th>
                            <td>{{ choice_ins.bread.price }}</td>
                        </tr>
                        <tr>
                            <td colspan="4"><img src="{{ choice_ins.bread.photo.url }}" alt=""></td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}