app/config/urls.py
import json
from ast import literal_eval

from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.urls import path, include

from config import settings
from posts.models import Post
from system.views import UserLoginView

User = get_user_model()


def get_literal_eval(eval_list):
    for data in eval_list:
        ret_list = literal_eval(data)

    return ret_list


def delete_exec(model, check_list):
    for obj in get_literal_eval(check_list):
        if model == 'account':
            User.objects.get(pk=int(obj['id'])).delete()
        elif model == 'post':
            Post.objects.get(pk=int(obj['id'])).delete()


def select_del(request):
    delete_exec(

        request.POST.get('tableIndex'),
        request.POST.getlist('checkList')
    )

    return HttpResponse(
        json.dumps({
            'result': 'success',
        }), content_type='application/json')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('del/', select_del, name='del'),
    path('', UserLoginView.as_view(), name='user-login'),
    path('system/', include('system.urls')),
    path('posts/', include('posts.urls')),
    path('items/', include('items.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/items/urls.py
from django.urls import path

from items.views import *

app_name = 'items'

urlpatterns = [
    path('', BreadsListView.as_view(), name='bread-list'),
    path('choice/', ChoiceListView.as_view(), name='choice-create'),
    path('package/<int:pk>/', PackageDetailView.as_view(), name='package-detail'),
    path('packageLike/', PackageLikeCreateView.as_view(), name='package-like'),
]

app/posts/urls.py
from django.urls import path

from posts.views import PostListView, post_create, PostUpdateView, PostDetailView

app_name = 'posts'

urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('update/<int:pk>/', PostUpdateView.as_view(), name='post-update'),
    path('create/', post_create, name='post-create'),
]

app/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    title = models.CharField(max_length=100, help_text='제목', )
    comment = models.TextField(max_length=100, help_text='내용', )
    photo = models.ImageField(upload_to="%Y/%m/%d")
    created_at = models.DateField(auto_now_add=True)

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )


class Comment(models.Model):
    content = models.TextField(help_text='내용', )

    post = models.ForeignKey(
        'posts.Post',
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )

app/posts/forms.py
from django import forms

from .models import Post, Comment


class PostCreateForm(forms.Form):
    photo = forms.ImageField(
        widget=forms.FileInput(
            # HTML위젯의 속성 설정
            # form-control-file클래스를 사용
            attrs={
                'class': 'form-control-file',
            }
        )
    )
    comment = forms.CharField(
        # 반드시 채워져 있을 필요는 없음
        required=False,
        # HTML랜더링 위젯으로 textarea를 사용
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
            }
        ),
    )

    def save(self, **kwargs):
        post = Post.objects.create(
            photo=self.cleaned_data['photo'],
            **kwargs,
        )
        comment_content = self.cleaned_data.get('comment')
        if comment_content:
            post.comments.create(
                author=post.author,
                content=comment_content,
            )
        return post


class CommentCreateForm(forms.Form):
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'rows': 2,
            }
        )
    )

    def save(self, post, **kwargs):
        content = self.cleaned_data['content']
        return post.comments.create(
            content=content,
            **kwargs,
        )


class PostForm(forms.ModelForm):
    comment = forms.CharField(
        label='내용',
        required=False,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'rows': 2,
            }
        )
    )

    class Meta:
        model = Post
        fields = [
            'title',
            'photo',
            'comment',
        ]
        widgets = {
            'photo': forms.ClearableFileInput(
                attrs={
                    'class': 'form-control-file',
                }
            ),
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            )

        }

    def save(self, *args, **kwargs):
        if self.errors:
            raise ValueError('폼의 유효성 검증에 실패하였습니다.')
        user_ins = kwargs['context'].user
        post = Post.objects.create(
            **self.cleaned_data,
            author=user_ins
        )
        return post


class PostUpdateForm(forms.ModelForm):
    comment = forms.CharField(
        label='내용',
        required=False,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'rows': 2,
            }
        )
    )

    class Meta:
        model = Post
        fields = [
            'title',
            'photo',
            'comment',
        ]
        widgets = {
            'photo': forms.ClearableFileInput(
                attrs={
                    'class': 'form-control-file',
                }
            ),
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            )

        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'content',
        ]
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'rows': 2,
                }
            )
        }

app/posts/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DetailView

from posts.forms import PostCreateForm, PostForm, PostUpdateForm
from posts.models import Post


def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save(context=request)
            return redirect('posts:post-list')
    form = PostForm
    context = {
        'form': form
    }
    return render(request, 'posts/post_create.html', context=context)


class PostListView(ListView):
    model = Post
    template_name = 'posts/post_list.html'
    context_object_name = 'post_lst'


class PostDetailView(DetailView):
    template_name = 'posts/post_detail.html'
    model = Post


class PostUpdateView(UpdateView):
    model = Post
    template_name = 'posts/post_update.html'
    form_class = PostUpdateForm
    success_url = reverse_lazy('posts:post-list')

app/templates/posts/post_base.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div>
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">게시글 번호</th>
                <th scope="col">작성자</th>
                <th scope="col">작성자 이미지</th>
                <th scope="col">제목</th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col">좋아요</th>
                <th scope="col">댓글 수</th>
            </tr>
            </thead>
            <tbody>
            {% for post in posts %}
                <tr>
                    <th scope="row">
                        <a href="{% url 'posts:post-detail' post_pk=post.pk %}" style="color: black">{{ post.pk }}</a>
                    </th>
                    <td>{{ post.user }}</td>
                    <td>
                        <img src="{{ post.user.img_profile_url }}"
                             style="width: 30px; height: 30px; border-radius: 100%;">
                    </td>
                    <td colspan="4">
                        <a href="{% url 'posts:post-detail' post_pk=post.pk %}"
                           style="color: black">{{ post.title }}</a>
                    </td>
                    <td>
                        <a href="{% url 'posts:post-detail' post_pk=post.pk %}"
                           style="color: black">{{ post.like_users.count }}</a>
                    </td>
                    <td>
                        <a href="{% url 'posts:post-detail' post_pk=post.pk %}"
                           style="color: black">{{ post.comment_set.count }}</a>
                    </td>
                </tr>
            {% endfor %}

            </tbody>

        </table>
        <div class="container text-center mt-1">
            <div>
                <form action="{% url 'posts:tag-search' %}" class="ml-md-auto mb-4">
                    <input type="text"
                           name="search_keyword"
                           class="form-control"
                           placeholder="태그를 찾아줍니다. like) HUS OKC">
                </form>
            </div>
            <a href="{% url 'posts:post-create' %}" class="btn btn-outline-primary"> + Add Post</a>
        </div>

    </div>
{% endblock %}

app/templates/posts/post_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    게시글 생성
{% endblock %}
{% block contents %}
    <div class="row">
        <div class="col col-lg-4 col-lg-offset-4 col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4">
            <form method="POST" enctype="multipart/form-data" class="form-group">
                {% csrf_token %}
                {% for field in form %}
                    <p>{{ field.label }}</p>
                    {{ field }}
                {% endfor %}
                <button type="submit">btn</button>
            </form>
        </div>
    </div>
{% endblock %}

app/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}게시글 상세{% endblock %}

{% load static %}
{% load bootstrap3 %}
{% block contents %}
{#    <div id="post-{{ post.pk }}" class="col col-lg-12">#}
{#        <div class="card">#}
{#            <div class="card-header">#}
{#                {{ post.title }}#}
{#            </div>#}
{#            <table class="table">#}
{#                <thead>#}
{#                <tr>#}
{#                    <th scope="col">{{ post.user.first_name }}</th>#}
{#                    <th scope=" col">{{ post.created_at }}</th>#}
{#                    <th scope="col">{{ post.id }}</th>#}
{#                </tr>#}
{#                </thead>#}
{#            </table>#}
{#            <div class="card-body">#}
{#                <img src="{{ post.image.url }}" class="card-img-top">#}
{#                <p class="card-text">{{ post.content }}</p>#}
{#                <p class="card-footer">{{ post.html|safe }}</p>#}

{#                <ul class="list-group">#}
{#                    {% for comment in post.comment_set.all %}#}
{#                        <li class="list-group-item ">#}
{#                            <strong>{{ comment.author }}</strong>#}
{#                            <span>{{ comment.html|safe }}</span>#}
{##}
{#                        </li>#}
{#                    {% endfor %}#}
{#                    {% if user.is_authenticated %}#}
{#                        <form action="{% url 'posts:post-like-toggle' post_pk=post.pk %}" method="POST">#}
{#                            {% csrf_token %}#}
{#                            <button class="btn btn-primary" type="submit">#}
{#                                {% if user in post.like_users.all %}#}
{#                                    좋아요 해제#}
{#                                {% else %}#}
{#                                    좋아요#}
{#                                {% endif %}#}
{#                            </button>#}
{#                        </form>#}
{#                    {% endif %}#}

{#                    <div>#}
{#                        <span>좋아하는 사람 </span>#}
{#                        <strong>{{ post.like_users.count }}</strong>#}
{#                    </div>#}

{#                </ul>#}
                <!--댓글 작성 form 구현-->
                <!-- 유저가 로그인을 한 경우에만 보여지도록 -->
{#                {% if user.is_authenticated %}#}
{#                    <form action="{% url 'posts:comment-create' post_pk=post.pk %}"#}
{#                          method="POST">#}
{#                        {% csrf_token %}#}
{#                        {{ comment_form.content }}#}
{#                        <button class="btn btn-primary btn-block"#}
{#                                type="submit">댓글 작성#}
{#                        </button>#}
{#                    </form>#}
{#                {% endif %}#}
            </div>
        </div>
    </div>
<div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">게시글 상세정보</div>
            <div class="panel-body">
                <table class="table table-bordered table-hover">
                    <tr>
                        <th><span style="color: red"></span>게시글번호</th>
                        <td colspan="3">
                            <input type="text" name="id" value="{{ object.id }}" class="form-control" disabled>
                        </td>
                    </tr>
                    <tr>
                        <th><span style="color: red"></span>제목</th>
                        <td>
                            <input type="text" class="form-control" name="company" id="company"
                                   value="{{ object.title }}">
                        </td>
                        <th><span style="color: red"></span>작성자</th>
                        <td><input type="text" class="form-control" name="name" value="{{ object.author }}"></td>
                    </tr>
                    <tr>
                        <th><span style="color: red"></span>생성일자</th>
                        <td>
                            <input type="date" class="form-control" name="due_date"
                                   value="{{ object.created_at|date:'Y-m-d' }}">
                        </td>
                        <th><span style="color: red"></span></th>
                        <td>
                        </td>
                    </tr>
                </table>
                <textarea name="memo" cols="30" rows="10" class="form-control">{{ object.comment }}</textarea>
                {% if object.photo %}
                    <div style="display: flex; justify-content: center;">
                        <img src="{{ object.photo.url }}" alt="" style="width: 1000px; height: 500px; padding: 50px;">
                    </div>

                {% else %}
                    {#                    <img src="#" alt="" style="width: 100%; height: 400px; padding: 50px;">#}
                {% endif %}
                <div class="regBtnWrap">
                    <div class="td_flex">
                        <input type="file" accept="image/png" class="form-control" name="image"
                               style="width: 200px;"
                               value="{{ object.image }}">
                        <a href="{% url 'posts:post-update' pk=post.pk %}" class="save btn btn-primary">수정</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/posts/post_list.html
{% extends "base.html" %}
{% block title %}게시글 목록{% endblock %}
{% load bootstrap3 %}
{% load static %}

{% block contents %}
    {#    <link rel="stylesheet" type="text/css" href="{% static 'css/system/post/get_accounts.css' %}">#}
    <script type="text/javascript" src="{% static 'js/system/post/get_post_script.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/tablesorter.js' %}"></script>


    {% csrf_token %}
    <div class="listView">
        <div class="row ">
            <div class="col col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 includeCheckBox">
                {% if user.type == 'SUPERVISOR' %}
                    <div class="listTopBtn">
                        <div class="right">
                            <button id="checkAll" class="listTopBtn__chk checkAll">전체 선택</button>
                            <button id="delBtn" class="listTopBtn__del delBtn" onclick="delModalShow()" disabled>게시글 삭제
                            </button>
                        </div>
                    </div>
                {% endif %}
                <table class="table table-bordered" id="myTable" role="grid">
                    <colgroup>
                        <col width="33%">
                        <col width="34%">
                        <col width="33%">
                    </colgroup>
                    <thead>
                    <tr>
                        <th>게시글번호<span class="glyphicon glyphicon-sort"></span></th>
                        <th>제목<span class="glyphicon glyphicon-sort"></span></th>
                        <th>내용<span class="glyphicon glyphicon-sort"></span></th>
                    </tr>
                    </thead>
                    <tbody aria-live="polite" aria-relevant="all">
                    {% for post in post_lst %}
                        <tr>
                            <td>
                                <a href="{% url 'posts:post-detail' pk=post.pk %}">{{ post.id }}</a>
                                <input type="checkbox" name="postCheck" value="{{ post.id }}"
                                       class="hidden_chk">
                            </td>
                            <td>{{ post.title }}</td>
                            <td>{{ post.comment }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div id="delModal" class="deleteModal">
        <div class="delete-modal-content">
            <div class="imgBox">
            </div>
            <div class="deleteCont">
                <p class="delMessage">정말 삭제하시겠습니까?</p>
                <p class="delSubMessage">한 번 삭제된 데이터는 복원이 불가능합니다.</p>
            </div>
            <div class="modalBtnWrap">
                <span class="modalBtn yes" onclick="infoDel('post');">예</span>
                <span class="modalBtn no" onclick="closeDelModal();">아니오</span>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/posts/post_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    게시글 수정
{% endblock %}
{% block contents %}
    <div class="row">
        <div class="col col-lg-4 col-lg-offset-4 col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4">
            <form method="POST" enctype="multipart/form-data" class="form-group">
                {% csrf_token %}
                {% for field in form %}
                    <p>{{ field.label }}</p>
                    {{ field }}
                {% endfor %}
                <button type="submit">btn</button>
            </form>
        </div>
    </div>
{% endblock %}

app/templates/posts/tag_post_list.html
{% extends 'base.html' %}
{% block content %}
<div>

    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">게시글 번호</th>
            <th scope="col">작성자</th>
            <th scope="col">작성자 이미지</th>
            <th scope="col">제목</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col">좋아요</th>
            <th scope="col">댓글 수</th>
        </tr>
        </thead>
        <tbody>
        {% for post in posts %}
        <tr>
            <th scope="row">
                <a href="{% url 'posts:post-detail' post_pk=post.pk %}" style="color: black">{{post.pk}}</a>
            </th>
            <td>{{post.user}}</td>
            <td>
                <img src="{{ post.user.img_profile_url }}" style="width: 30px; height: 30px; border-radius: 100%;">
            </td>
            <td colspan="4">
                <a href="{% url 'posts:post-detail' post_pk=post.pk %}" style="color: black">{{post.title}}</a>
            </td>
            <td>
                <a href="{% url 'posts:post-detail' post_pk=post.pk %}"
                   style="color: black">{{post.like_users.count}}</a>
            </td>
            <td>
                <a href="{% url 'posts:post-detail' post_pk=post.pk %}"
                   style="color: black">{{post.comment_set.count}}</a>
            </td>
        </tr>
        {% endfor %}

        </tbody>

    </table>
    <div class="container text-center mt-1">
        <div>
            <form action="{% url 'posts:tag-search' %}" class="ml-md-auto mb-4">
                <input type="text"
                       name="search_keyword"
                       class="form-control"
                       placeholder="태그를 찾아줍니다. like) HUS OKC">
            </form>
        </div>
        <a href="{% url 'posts:post-create' %}" class="btn btn-outline-primary"> + Add Post</a>
    </div>

</div>
{% endblock %}