app/config/urls.py
import json
from ast import literal_eval

from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.urls import path, include

from config import settings
from posts.models import Post
from system.views import UserLoginView

User = get_user_model()


def get_literal_eval(eval_list):
    for data in eval_list:
        ret_list = literal_eval(data)

    return ret_list


def delete_exec(model, check_list):
    for obj in get_literal_eval(check_list):
        if model == 'account':
            User.objects.get(pk=int(obj['id'])).delete()
        elif model == 'post':
            Post.objects.get(pk=int(obj['id'])).delete()


def select_del(request):
    delete_exec(

        request.POST.get('tableIndex'),
        request.POST.getlist('checkList')
    )

    return HttpResponse(
        json.dumps({
            'result': 'success',
        }), content_type='application/json')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('del/', select_del, name='del'),
    path('', UserLoginView.as_view(), name='user-login'),
    path('system/', include('system.urls')),
    path('posts/', include('posts.urls')),
    path('items/', include('items.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/items/urls.py
from django.urls import path

from items.views import *

app_name = 'items'

urlpatterns = [
    path('', BreadsListView.as_view(), name='bread-list'),
    path('choice/', ChoiceListView.as_view(), name='choice-create'),
    path('package/<int:pk>/', PackageDetailView.as_view(), name='package-detail'),
    path('packageLike/', PackageLikeCreateView.as_view(), name='package-like'),
]

app/system/urls.py
from django.urls import path

from system.views import user_logout, UserLoginView, UserListView, UserUpdateView, user_create

app_name = 'system'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='user-login'),
    path('logout/', user_logout, name='user-logout'),


    path('user/', UserListView.as_view(), name='user-list'),
    path('user/<int:pk>/', UserUpdateView.as_view(), name='user-update'),
    path('user/create/', user_create, name='user-create'),
]

app/system/models.py
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    USERTYPE = (
        ('CONSUMER', '소비자'),
        ("SUPERVISOR", "최고관리자"),
    )
    type = models.CharField(help_text='계정 유형', max_length=20, choices=USERTYPE, default='SUPERVISOR')
    is_activate = models.BooleanField(help_text='계정 활성화 여부', null=True, blank=True)

    class Meta:
        verbose_name = '사용자'
        verbose_name_plural = '사용자들 - User'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if len(self.password) <= 20:
            self.password = make_password(self.password)
            self.save()


class UserLogManagerQuerySet(models.QuerySet):
    def users_login_time(self, login, logout):
        return self.filter(login__gte=login, logout__lte=logout)

    def user_login_time(self, login, logout, user):
        return self.filter(login__gte=login, logout__lte=logout, user=user)


class UserLog(models.Model):
    login = models.DateTimeField(help_text='로그인 시간', blank=True, null=True, )
    logout = models.DateTimeField(help_text='로그아웃 시간', blank=True, null=True, )
    user = models.ForeignKey(User, on_delete=models.CASCADE, help_text='유저')

    objects = models.Manager()
    times = UserLogManagerQuerySet.as_manager()

    class Meta:
        verbose_name = '유저 접속시간'
        verbose_name_plural = '유저들의 접속 기간 - UserLog'

    @property
    def calculate_time(self):
        return (self.logout - self.login).seconds

    @property
    def convert_to_minute(self):
        return self.calculate_time // 60

app/system/views.py
from datetime import datetime

from django.contrib.auth import logout, authenticate, login, get_user_model
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView, UpdateView

from system.form.user import LoginForm, UserForm, UserUpdateForm
from system.models import UserLog

User = get_user_model()


class UserLoginView(FormView):
    template_name = 'system/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('system:user-list')

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']

        user = authenticate(self.request, username=username, password=password)
        if user:
            login(self.request, user)
            UserLog.objects.create(user=user, login=datetime.now())
        return super().form_valid(form)


def user_logout(request):
    log = UserLog.objects.filter(user=request.user).last()
    log.logout = datetime.now()
    log.save()
    logout(request)
    next_path = request.GET.get('next')
    if next_path:
        return redirect(next_path)
    return redirect('system:user-list')


class UserListView(ListView):
    model = User
    form = UserForm
    template_name = 'system/list_account.html'
    context_object_name = 'user_lst'


class UserUpdateView(UpdateView):
    model = User
    template_name = 'system/update_account.html'
    form_class = UserUpdateForm
    success_url = reverse_lazy('system:user-list')


def user_create(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('system:user-list')
    form = UserForm
    context = {
        'form': form
    }
    return render(request, 'system/create_account.html', context=context)

app/templates/system/create_account.html
{% extends "base.html" %}
{% load static %}
{% block title %}사용자 추가{% endblock %}
{% block contents %}
    {#    <link rel="stylesheet" type="text/css" href="{% static 'css/account/add_account.css' %}">#}
    {#    <script type="text/javascript" src="{% static 'js/account/base_script.js' %}"></script>#}


    <div class="row">
        <div class="col col-lg-4 col-lg-offset-4 col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4">
            {{ error }}
        </div>
    </div>
    <div class="row">
        <div class="col col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3">
            <form method="POST">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.label == "계정 활성화 여부" %}
                        <div class="form-group">
                            <span class="form-name">계정 활성화 여부</span>
                            <label class="switch">
                                <input type="checkbox" class="switch_input" id="is_activate" name="is_activate"
                                       value="True">
                                <span class="stat on">ON</span>
                                <span class="stat off">OFF</span>
                                <span class="handle"></span>
                            </label>
                        </div>
                    {% else %}
                        <div class="form-group">
                            <span class="field-label">{{ field.label }}</span>
                            {{ field }}
                        </div>
                    {% endif %}
                    {% if field.errors %}
                        <span style="color: red">{{ field.errors }}</span>
                    {% endif %}
                {% endfor %}

                <div class="regBtnWrap">
                    <button type="submit" class="btn btn-primary" style="float: right;">등록</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

app/templates/system/list_account.html
{% extends "base.html" %}
{% block title %}사용자 목록{% endblock %}
{% load bootstrap3 %}
{% load static %}

{% block contents %}
    {#    <link rel="stylesheet" type="text/css" href="{% static 'css/system/account/get_accounts.css' %}">#}
    <script type="text/javascript" src="{% static 'js/system/user/get_accounts_script.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/tablesorter.js' %}"></script>


    {% csrf_token %}
    <div class="listView">
        <div class="row ">
            <div class="col col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 includeCheckBox">
                <div class="listTopBtn">
                    <div class="right">
                        <button id="checkAll" class="listTopBtn__chk checkAll">전체 선택</button>
                        <button id="delBtn" class="listTopBtn__del delBtn" onclick="delModalShow()" disabled>사용자 정보 삭제
                        </button>
                    </div>
                </div>
                <table class="table table-bordered" id="myTable" role="grid">
                    <colgroup>
                        <col width="20%">
                        <col width="24%">
                        <col width="18%">
                        <col width="23%">
                        <col width="15%">
                    </colgroup>
                    <thead>
                    <tr>
                        <th>사용자 계정 <span class="glyphicon glyphicon-sort"></span></th>
                        <th>이름 <span class="glyphicon glyphicon-sort"></span></th>
                        <th>계정 유형 <span class="glyphicon glyphicon-sort"></span></th>
                        <th>관리자 여부</th>
                        <th>활성화 여부</th>
                    </tr>
                    </thead>
                    <tbody aria-live="polite" aria-relevant="all">
                    {% for account in user_lst %}
                        <tr>
                            {% if not account.type == 'SUPERVISOR' %}
                                <td>
                                    <a href="{% url 'system:user-update' pk=account.pk %}">{{ account.id }}</a>
                                    <input type="checkbox" name="accountCheck" value="{{ account.id }}"
                                           class="hidden_chk">
                                </td>
                                <td>{{ account.username }}</td>
                                <td>{{ account.type }}</td>
                                {% if account.type == 'SUPERVISOR' %}
                                    <td><span class="glyphicon glyphicon-ok"></span></td>
                                {% else %}
                                    <td><span class="glyphicon glyphicon-remove"></span></td>
                                {% endif %}
                                {% if account.is_activate == True %}
                                    <td><span class="glyphicon glyphicon-ok"></span></td>
                                {% else %}
                                    <td><span class="glyphicon glyphicon-remove"></span></td>
                                {% endif %}
                            {% else %}
                                <td>
                                    {{ account.id }}
                                    <input type="checkbox" name="accountCheck" value="{{ account.id }}"
                                           class="hidden_chk">
                                </td>
                                <td>{{ account.username }}</td>
                                <td>{{ account.type }}</td>
                                {% if account.type == 'SUPERVISOR' %}
                                    <td><span class="glyphicon glyphicon-ok"></span></td>
                                {% else %}
                                    <td><span class="glyphicon glyphicon-remove"></span></td>
                                {% endif %}
                                {% if account.is_activate == True %}
                                    <td><span class="glyphicon glyphicon-ok"></span></td>
                                {% else %}
                                    <td><span class="glyphicon glyphicon-remove"></span></td>
                                {% endif %}
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div id="delModal" class="deleteModal">
        <div class="delete-modal-content">
            <div class="imgBox">
            </div>
            <div class="deleteCont">
                <p class="delMessage">정말 삭제하시겠습니까?</p>
                <p class="delSubMessage">한 번 삭제된 데이터는 복원이 불가능합니다.</p>
            </div>
            <div class="modalBtnWrap">
                <span class="modalBtn yes" onclick="infoDel('account');">예</span>
                <span class="modalBtn no" onclick="closeDelModal();">아니오</span>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/system/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Login
{% endblock %}
{% block contents %}
    <div class="row">
        <div class="col col-lg-4 col-lg-offset-4 col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4">
            <form method="POST">
                {% csrf_token %}
                {% if form.non_field_errors %}
                    {# forms.error의 '__all__'은 form.non_field_errors 로 표현할 수 있다. #}
                    {{ form.non_field_errors }}
                {% endif %}
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <input type="{{ field.field.widget.input_type }}" class="form-control"
                               id="{{ field.id_for_label }}"
                               placeholder="{{ field.label }}" name="{{ field.name }}"/>
                    </div>
                    {% if field.errors %}
                        <span style="color: red">{{ field.errors }}</span>
                    {% endif %}
                {% endfor %}
                <button type="reset" class="btn btn-primary" style="float: right;">취소</button>
                <button type="submit" class="btn btn-primary" style="float: right;margin-right: 1%">로그인</button>

            </form>
        </div>
    </div>
{#    <div class="footer" style="margin-left: 20px">#}
{#        <div>신한 세라믹 테스트용</div>#}
{#    </div>#}

{% endblock %}

app/templates/system/update_account.html
{% extends "base.html" %}
{% load static %}
{% block title %}사용자 추가{% endblock %}
{% block contents %}

    <div class="row">
        <div class="col col-lg-4 col-lg-offset-4 col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4">
            {{ error }}
        </div>
    </div>
    <div class="row">
        <div class="col col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3">
            <form method="POST">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.label == "계정 활성화 여부" %}
                        <div class="form-group">
                            <span class="form-name">계정 활성화 여부</span>
                            <label class="switch">
                                <input type="checkbox" class="switch_input" id="is_activate" name="is_activate"
                                       value="True">
                                <span class="stat on">ON</span>
                                <span class="stat off">OFF</span>
                                <span class="handle"></span>
                            </label>
                        </div>
                    {% else %}
                        <div class="form-group">
                            <span class="field-label">{{ field.label }}</span>
                            {{ field }}
                        </div>
                    {% endif %}
                    {% if field.errors %}
                        <span style="color: red">{{ field.errors }}</span>
                    {% endif %}
                {% endfor %}

                <div class="regBtnWrap">
                    <button type="submit" class="btn btn-primary" style="float: right;">수정</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}