app/config/urls.py
import json
from ast import literal_eval

from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.urls import path, include

from config import settings
from posts.models import Post
from system.views import UserLoginView

User = get_user_model()


def get_literal_eval(eval_list):
    for data in eval_list:
        ret_list = literal_eval(data)

    return ret_list


def delete_exec(model, check_list):
    for obj in get_literal_eval(check_list):
        if model == 'account':
            User.objects.get(pk=int(obj['id'])).delete()
        elif model == 'post':
            Post.objects.get(pk=int(obj['id'])).delete()


def select_del(request):
    delete_exec(

        request.POST.get('tableIndex'),
        request.POST.getlist('checkList')
    )

    return HttpResponse(
        json.dumps({
            'result': 'success',
        }), content_type='application/json')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('del/', select_del, name='del'),
    path('', UserLoginView.as_view(), name='user-login'),
    path('system/', include('system.urls')),
    path('posts/', include('posts.urls')),
    path('items/', include('items.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/items/urls.py
from django.urls import path

from items.views import *

app_name = 'items'

urlpatterns = [
    path('', BreadsListView.as_view(), name='bread-list'),
    path('choice/', ChoiceListView.as_view(), name='choice-create'),
    path('package/<int:pk>/', PackageDetailView.as_view(), name='package-detail'),
    path('packageLike/', PackageLikeCreateView.as_view(), name='package-like'),
]

app/posts/urls.py
from django.urls import path

from posts.views import PostListView, post_create, PostUpdateView, PostDetailView

app_name = 'posts'

urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('update/<int:pk>/', PostUpdateView.as_view(), name='post-update'),
    path('create/', post_create, name='post-create'),
]

app/system/urls.py
from django.urls import path

from system.views import user_logout, UserLoginView, UserListView, UserUpdateView, user_create

app_name = 'system'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='user-login'),
    path('logout/', user_logout, name='user-logout'),


    path('user/', UserListView.as_view(), name='user-list'),
    path('user/<int:pk>/', UserUpdateView.as_view(), name='user-update'),
    path('user/create/', user_create, name='user-create'),
]

app/templates/base.html
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <script type="text/javascript" src="{% static 'js/common/jquery-latest.js' %}"></script>

    {# jquery#}
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"
            integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>


    <link rel="stylesheet" type="text/css" href="{% static 'css/common/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/common/bootstrap-theme.min.css' %}">
    <script type="text/javascript" src="{% static 'js/common/bootstrap.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/common/moment-with-locales.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/common/bootstrap-datetimepicker.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/common/jquery.tablesorter.combined.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/common/jquery.tablesorter.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/common/jquery.tablesorter.widgets.min.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/common/theme.default.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/common/tableexport.css' %}">

    <script type="text/javascript" src="{% static 'js/common/xlsx.core.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/common/Blob.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/common/FileSaver.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/common/tableexport.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/common/Chart.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/common/chartjs-plugin-datalabels.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/common/jszip.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/common/jszip-utils.min.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/pdfobject.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/common/exceljs.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/common/table2excel.core.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/common/choices.min.css' %}">
    <script type="text/javascript" src="{% static 'js/common/choices.min.js' %}"></script>


    {% load bootstrap3 %} {# imports bootstrap3 #}
    {% bootstrap_css %} {# Embeds Bootstrap CSS #}
    {% block extrahead %}       {# Embeds Extra Resources #}
    {% endblock %}              {# Ends Extra Resources #}
    {% block header %}
    {% endblock %}
</head>

<body>
{% include "nav.html" %}
<div class="container-fluid">
    <div class="row">
        <div class="col col-lg-12 text-center">
            <h1>{% block title %}(no title){% endblock %}</h1>
        </div>
    </div>
    {% block contents %}
    {% endblock %}
</div>
</body>
</html>

app/templates/nav.html
<nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse"
                    aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="">도담도담</a>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav" id="menu">
                {% if user.type == 'SUPERVISOR' %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">커뮤니티<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <p class="btn btn-secondary dropdown-toggle production_list_title produce_plan"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                커뮤니티
                            </p>
                            <li><a href="{% url 'posts:post-create' %}"><span class="glyphicon glyphicon-plus"></span>게시글
                                등록</a></li>
                            <li><a href="{% url 'posts:post-list' %}"><span class="glyphicon glyphicon-list"></span>게시글
                                목록</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">시스템 관리<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <p class="btn btn-secondary dropdown-toggle production_list_title produce_plan"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">사용자 설정</p>
                            <li><a href="{% url 'system:user-create' %}"><span class="glyphicon glyphicon-plus"></span>사용자
                                등록</a></li>
                            <li><a href="{% url 'system:user-list' %}"><span class="glyphicon glyphicon-list"></span>사용자
                                목록</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">빵 묶음<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            {#                            <p class="btn btn-secondary dropdown-toggle production_list_title produce_plan"#}
                            {#                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
                            {#                                커뮤니티#}
                            {#                            </p>#}
{#                            <li>#}
{#                                <a href="{% url 'posts:post-create' %}">#}
{#                                    <span class="glyphicon glyphicon-plus"></span>#}
{#                                    게시글 등록#}
{#                                </a>#}
{#                            </li>#}
                            <li>
                                <a href="{% url 'items:bread-list' %}">
                                    <span class="glyphicon glyphicon-list"></span>
                                    게시글 목록
                                </a>
                            </li>
                        </ul>
                    </li>
                {% endif %}
            </ul>


            {% if user.pk is None %}
                <ul class="nav navbar-nav navbar-right">
                    <a class="navbar-brand" href="{% url 'system:user-login' %}">로그인</a>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <a class="navbar-brand" href="{% url 'system:user-logout' %}"><span
                            class="text-primary">{{ user.username }} </span>로그아웃</a>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>